# Generated by Django 4.2.6 on 2024-07-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='black_profile_img.jpeg', upload_to='profile_images'),
        ),
    ]
